server:
  port: 80
spring:
  application:
    name: gateway-server

  #REDIS (RedisProperties)
  # Redis数据库索引（默认为0）
  redis:
    database: 4
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口(默认6379)
    port: 6380
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000

---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          # 表示可以通过注册中心的服务名进行路由转发
          enabled: false
          #将请求路径上的服务名配置为小写
          lowerCaseServiceId: true
      routes:
        #会员服务,表示路由的唯一id
        - id: member-server
          #转发地址，指向注册中心的服务(lb://开头代表在注册中心中获取服务)，使用服务名方便后面微服务集群的搭建
          uri: lb://member-server
          #表示要进行断言(要拦截的请求)
          predicates:
            #表示path地址，根据url，以member开头的会被转发到member-server服务
            - Path=/member/**
          #过滤器
          filters:
            #转发前去掉/member前缀
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@uriKeyResolver}'         #用于限流解析器的Bean对象名字
                redis-rate-limiter.replenishRate: 1    #令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 3  #令牌桶总容量
        #微信服务
        - id: weixin-server
          uri: lb://weixin-server
          predicates:
            - Path=/weixin/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}' #用于限流解析器的Bean对象名字
                redis-rate-limiter.replenishRate: 3    #令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 10  #令牌桶总容量
        #短信服务
        - id: phone-server
          uri: lb://phone-server
          predicates:
            - Path=/phone/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}'         #用于限流解析器的Bean对象名字
                redis-rate-limiter.replenishRate: 1    #令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 3  #令牌桶总容量
        #商品服务
        - id: goods-server
          uri: lb://goods-server
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}' #用于限流解析器的Bean对象名字
                redis-rate-limiter.replenishRate: 3    #令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 10  #令牌桶总容量

#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/